---
title: "script"
author: "jincanzhi"
date: "2025-12-24"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(vegan)
library(rstatix)
library(agricolae)
library(patchwork)
library(cowplot)
library(scales)
library(RColorBrewer)
library(tibble) 
library(ggpie)
library(ggsignif)
set.seed(113)
knitr::opts_knit$set(root.dir =dirname(rstudioapi::getSourceEditorContext()[["path"]]))
```

#wilcox
```{r}
ko_table <- read.delim("./data/Bacteria.cazy.anno.profile",row.names = 1,check.names = F)
KO_list <- row.names(ko_table)

alpha <- 0.05
res_list <- list()

for (ko in KO_list) {
  rp <- as.numeric(ko_table[ko, 1:17])
  rs <- as.numeric(ko_table[ko, 18:34])
  
  tmp_data <- data.frame(
    Value = c(rp, rs),
    Group = factor(rep(c("RP", "RS"), each = 17), levels = c("RP", "RS"))
  )
  
  wt_greater <- wilcox_test(Value ~ Group, data = tmp_data,
                            paired = TRUE, exact = FALSE,
                            alternative = "greater")
  wt_less    <- wilcox_test(Value ~ Group, data = tmp_data,
                            paired = TRUE, exact = FALSE,
                            alternative = "less")
  
  res_list[[ko]] <- data.frame(
    CAZy_Family = ko,
    W_greater   = wt_greater$statistic,
    p_greater   = wt_greater$p,
    W_less      = wt_less$statistic,
    p_less      = wt_less$p,
    median_RP   = median(rp, na.rm = TRUE),
    median_RS   = median(rs, na.rm = TRUE),
    stringsAsFactors = FALSE
  )
}

results_df <- do.call(rbind, res_list)

results_df$p_greater_adj <- p.adjust(results_df$p_greater, method = "fdr")
results_df$p_less_adj    <- p.adjust(results_df$p_less,    method = "fdr")

results_df$Direction <- with(results_df, {
  dir <- rep("NS", nrow(results_df))
  
  idx_g <- p_greater_adj < alpha & p_less_adj >= alpha
  dir[idx_g] <- "greater"
  idx_l <- p_less_adj < alpha & p_greater_adj >= alpha
  dir[idx_l] <- "less"
  
  idx_both <- p_greater_adj < alpha & p_less_adj < alpha
  pick_greater <- idx_both & (p_greater_adj <= p_less_adj)
  pick_less    <- idx_both & (p_less_adj  <  p_greater_adj)
  dir[pick_greater] <- "greater"
  dir[pick_less]    <- "less"
  
  dir
})

results_df$W_signif <- ifelse(results_df$Direction == "greater",
                              results_df$W_greater,
                              ifelse(results_df$Direction == "less",
                                     results_df$W_less, NA))
results_df$p_adj_signif <- ifelse(results_df$Direction == "greater",
                                  results_df$p_greater_adj,
                                  ifelse(results_df$Direction == "less",
                                         results_df$p_less_adj, NA))

final_df <- results_df[, c("CAZy_Family", "Direction", "W_signif", "p_adj_signif",
                           "median_RP", "median_RS")]
final_df$Direction
names(final_df)[3:4] <- c("W", "p_adj")
final_df$Direction <- ifelse(final_df$Direction == "greater", "RP_enrich",
                             ifelse(final_df$Direction == "less", "RS_enrich", "NS"))
write.csv(final_df, "./data/cazyme_wilcox_results.csv", row.names = FALSE)
```

#Figure6ABC
```{r}
raw_df <- read.table("./data/cazyme.diversity.index.txt",header=T,row.names = 1)
metadata <- read.csv("./data/metadata.csv",row.names = 1)
merge_df <- merge(raw_df, metadata, by.x = 'row.names', by.y = 'row.names')
fin_df <- merge_df[c("region", "shannon")]
names(fin_df)[1] <- "Group"

fin_df$Group <- factor(fin_df$Group, levels = c("RP", "RS"))

wilcox_res <- wilcox_test(shannon ~ Group, data = fin_df, exact = FALSE,alternative = "greater")
p_value <- wilcox_res$p

if (p_value < 0.001) {
  sig_label <- "***"
} else if (p_value < 0.01) {
  sig_label <- "**"
} else if (p_value < 0.05) {
  sig_label <- "*"
} else {
  sig_label <- "ns"
}

p1 <- ggplot(fin_df, aes(x = Group, y = shannon)) + 
  geom_point(aes(color = Group), position = position_jitter(width = 0.15), 
             alpha = 0.8, size = 4, stroke = 0) +
  geom_boxplot(width = 0.3, alpha = 0.2, na.rm = TRUE) +   
  geom_violin(width = 0.5, alpha = 0.2, na.rm = TRUE) +  
  geom_signif(comparisons = list(c("RP", "RS")),
              annotations = sig_label,
              tip_length = 0.02,
              color = "black") +
  theme_classic(base_size = 10) +
  scale_x_discrete(labels = c("Rhizoplane", "Rhizosphere")) + 
  scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  scale_fill_manual(values = c("#D55E00", "#0072B2")) + 
  theme(
    axis.title = element_text(size = 10, color = "black", face = "bold"),
    axis.text = element_text(size = 10, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.ticks = element_line(linewidth = 0.6, color = "black"),
    axis.line = element_line(linewidth = 0.6, color = "black"),
    panel.border = element_rect(fill = NA, color = "black", linewidth = 0.8),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    legend.position = "none"
  ) + 
  labs(
    x = NULL,
    y = "Shannon"
  )+ 
  coord_cartesian(ylim = c(NA, max(fin_df$shannon, na.rm = TRUE) * 1.02))

fin_df <- merge_df[c("region", "simpson")]
names(fin_df)[1] <- "Group"

fin_df$Group <- factor(fin_df$Group, levels = c("RP", "RS"))

wilcox_res <- wilcox_test(simpson ~ Group, data = fin_df, exact = FALSE,paired = TRUE,alternative = "greater")
p_value <- wilcox_res$p

if (p_value < 0.001) {
  sig_label <- "***"
} else if (p_value < 0.01) {
  sig_label <- "**"
} else if (p_value < 0.05) {
  sig_label <- "*"
} else {
  sig_label <- "ns"
}


p2 <- ggplot(fin_df, aes(x = Group, y = simpson)) + 
  geom_point(aes(color = Group), position = position_jitter(width = 0.15), 
             alpha = 0.8, size = 4, stroke = 0) +
  geom_boxplot(width = 0.3, alpha = 0.2, na.rm = TRUE) +   
  geom_violin(width = 0.5, alpha = 0.2, na.rm = TRUE) +  
  geom_signif(comparisons = list(c("RP", "RS")),
              annotations = sig_label,
              tip_length = 0.02,
              color = "black") +
  theme_classic(base_size = 10) +
  scale_x_discrete(labels = c("Rhizoplane", "Rhizosphere")) + 
  scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  scale_fill_manual(values = c("#D55E00", "#0072B2")) + 
  theme(
    axis.title = element_text(size = 10, color = "black", face = "bold"),
    axis.text = element_text(size = 10, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.ticks = element_line(linewidth = 0.6, color = "black"),
    axis.line = element_line(linewidth = 0.6, color = "black"),
    panel.border = element_rect(fill = NA, color = "black", linewidth = 0.8),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    legend.position = "none"
  ) + 
  labs(
    x = NULL,
    y = "Simpson"
  )+ 
  coord_cartesian(ylim = c(NA, max(fin_df$simpson, na.rm = TRUE) * 1.002))

##beta
ko_abundance<-read.delim("./data/Bacteria.cazy.anno.profile",row.names = 1)
metadata <- read.csv("./data/metadata.csv", row.names = 1, stringsAsFactors = FALSE)

ko_t <- t(ko_abundance)
bray_dist <- vegdist(ko_t, method = "bray", na.rm = TRUE)


pcoa_sig <- adonis2(bray_dist ~ region, data = metadata, permutations = 1000)
variance <- pcoa_sig['Model', 'R2']
p.val <- pcoa_sig['Model', 'Pr(>F)']

cmdscale_total <- cmdscale(bray_dist, eig = T)
eig <- cmdscale_total$eig

points <- data.frame(cmdscale_total$points)
data_df <- cbind(points, Group = metadata[rownames(points),])%>%
  mutate(Group.region = case_when(
    Group.region == "RP" ~ "Rhizoplane",
    Group.region == "RS" ~ "Rhizosphere",
    TRUE ~ Group.region
  ))
names(data_df)[names(data_df) == "Group.region"] <- "region"

p_text <- ifelse(p.val < 0.001, "p < 0.001", 
                 ifelse(p.val < 0.01, "p < 0.01", 
                        ifelse(p.val < 0.05, "p < 0.05", paste0("p = ", format(p.val, digits = 2)))))

p3<- ggplot(data_df, aes(x = X1, y = X2, color = region)) + 
    geom_point(size = 4, alpha = 1) + 
    stat_ellipse(level = 0.95, type = "norm", linewidth = 0.8, show.legend = FALSE) +
    labs(x = paste('PCoA 1 (', format(100*eig[1]/sum(eig), digits=4), '%)', sep = ''),
         y = paste('PCoA 2 (', format(100*eig[2]/sum(eig), digits=4), '%)', sep = '')) + 
    ggtitle(paste(format(100*variance, digits = 3), '% of variance; ', p_text, sep = '')) +
    scale_color_manual(values = c("#D55E00", "#0072B2")) + 
    scale_fill_manual(
        values = c("#D55E00", "#0072B2"),
        labels = c("Rhizoplane", "Rhizosphere"),
        name = "Region"
    ) +
    theme_classic(base_size = 10) +
    theme(plot.title = element_text(size = 10, color = 'black', hjust = 0.5), 
          plot.subtitle = element_text(size = 10, color = 'black', hjust = 0.5), 
          axis.title = element_text(size = 10, color = "black", face = "bold"),
          axis.text = element_text(size = 10, color = "black"),
          axis.ticks = element_line(linewidth = 0.6, color = "black"),
          axis.line = element_line(linewidth = 0.6, color = "black"),
          panel.border = element_rect(
            fill = NA, color = "black", linewidth = 0.8
          ),
          panel.grid = element_blank(),
          panel.background = element_blank(),
          legend.key.size = unit(0.5, 'cm'),
          legend.box.spacing = unit(0.5,"cm"),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          legend.position = 'none')

combined_plot <- (p1 + p2 + p3) + 
  plot_layout(
    nrow = 1,
    widths = c(1, 1, 2),
    heights = c(1, 1, 1)
  )
height <-7
width <- 16
ggsave(combined_plot, filename = "./Figure/Figure6ABC.png", width = width, height = height, dpi = 300, device = 'png', bg = 'white')
ggsave(combined_plot, filename = "./Figure/Figure6ABC.pdf", width = width, height = height, dpi = 300, device = 'pdf', bg = 'white')
```

#Figure6D
```{r}
cazy_abundance <- read.delim("./data/Bacteria.cazy.anno.profile",row.names = 1)
cazy_abundance <- cazy_abundance %>%
  mutate(
    Class = substr(rownames(.), 1, 2),
    Class = ifelse(Class == "CB", "CBM", Class)
  )
df <- cazy_abundance %>%
  group_by(Class) %>%
  summarise(
    across(where(is.numeric), ~sum(.x, na.rm = TRUE)),
    .groups = 'drop'
  ) %>%
  column_to_rownames("Class")


rp_cols <- grepl("RP", colnames(df))
rs_cols <- grepl("RS", colnames(df))

rp_sum <- rowSums(df[, rp_cols, drop = FALSE])
rs_sum <- rowSums(df[, rs_cols, drop = FALSE])

result <- data.frame(
  cazyme = rownames(df),
  Rhizoplane = rp_sum,
  Rhizosphere = rs_sum
)

df_long <- result %>%
  pivot_longer(
    cols = -cazyme,
    names_to = "Group",
    values_to = "Value"
  )

p4<-ggplot(df_long, aes(x = cazyme, y = Value, fill = Group)) +
  geom_col(position = "fill", width = 0.7,color = "black") +
  scale_fill_manual(
    values = c("Rhizoplane" = "#D55E00", "Rhizosphere" = "#0072B2"),
    labels = c("Rhizoplane", "Rhizosphere"),
    name = "Region"
  ) +
  labs(
    title = NULL,
    x = "CAZy Family",
    y = "Abundance"
  ) +
  theme_classic(base_size = 10) +
  theme(axis.title = element_text(size = 10, color = 'black',face = "bold"), 
        axis.text = element_text(size = 10, color = 'black'), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, color = "black",linewidth = 1),
        legend.position = "none",
        legend.text = element_text(size = 9),
        legend.title = element_text(size = 10, face = "bold"),
        legend.background = element_blank()
        )


results <- read.csv("./data/cazyme_wilcox_results.csv")
classified_data <- results %>%
  mutate(
    Group = case_when(
      str_detect(CAZy_Family, "^CBM") ~ "CBM", 
      str_detect(CAZy_Family, "^AA")  ~ "AA",
      str_detect(CAZy_Family, "^GH")  ~ "GH",
      str_detect(CAZy_Family, "^GT")  ~ "GT",
      str_detect(CAZy_Family, "^PL")  ~ "PL",
      str_detect(CAZy_Family, "^CE")  ~ "CE",
    )
  )

count_data <- classified_data %>%
  filter(Direction %in% c("RP_enrich", "RS_enrich")) %>%
  count(Group, Direction) %>%
  complete(Group = c("AA", "CBM", "GH", "GT", "PL", "CE"), 
           Direction = c("RP_enrich", "RS_enrich"),
           fill = list(n = 0)) %>%
  mutate(
    Group = factor(Group, levels = c("AA", "CBM", "GH", "GT", "PL", "CE")),
    Direction = factor(Direction, levels = c("RP_enrich", "RS_enrich"))
  )
group_order <- count_data %>%
  filter(Direction == "RP_enrich") %>%
  arrange(desc(n)) %>%
  pull(Group) %>%
  as.character() %>%
  unique()

all_groups <- c("AA", "CBM", "GH", "GT", "PL", "CE")

count_data <- count_data %>%
  mutate(Group = factor(Group, levels = group_order))

p5 <- ggplot(count_data, aes(x = Group, y = n, fill = Direction)) +
  geom_col(position = position_dodge(0.8), width = 0.7, color = "black") +
  scale_fill_manual(
    values = c("RP_enrich" = "#D55E00", "RS_enrich" = "#0072B2"),
    labels = c("Rhizoplane", "Rhizosphere"),
    name = "Region"
  ) +
  labs(
    x = "CAZy Family",
    y = "Numbers"
  ) +
  theme_classic(base_size = 10) +
  theme(axis.title = element_text(size = 10, color = 'black',face = "bold"), 
        axis.text = element_text(size = 10, color = 'black'), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA, color = "black",linewidth = 1),
        legend.position = "top",
        legend.text = element_text(size = 9),
        legend.title = element_text(size = 10, face = "bold"),
        legend.background = element_blank()
  )+
  geom_text(
    aes(label = n),
    position = position_dodge(0.8),
    vjust = -0.3,
    size = 3,
    fontface = "bold"
  ) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.1)),
    breaks = scales::pretty_breaks(n = 6)
  )

combined_plot <- 
  p1 + p2 + p3 + p4 + p5 +
  plot_layout(
    design = "
    ABC
    DDE
    ",
    widths = c(1, 1, 3),
    heights = c(1, 1)
  )

ggsave("./Figure/Figure6ABCDE.pdf", plot = combined_plot,width = 17, height = 17, units = "cm",dpi = 600)
ggsave("./Figure/Figure6ABCDE.png", plot = combined_plot,width = 17, height = 17, units = "cm",dpi = 600)
```

#Figure6F
```{r}

combined_df <- read.csv("./data/cazy_tax.csv")

species_stats <- combined_df %>%
  filter(Species != "Others") %>%
  count(Species, sort = TRUE)

species_levels <- c(species_stats$Species, "Others")

n_main_species <- length(species_levels) - 1
color_palette <- if (n_main_species <= 8) {
  brewer.pal(n_main_species, "Set2")
} else {
  colorRampPalette(brewer.pal(8, "Set2"))(n_main_species)
}
names(color_palette) <- head(species_levels, -1)
color_palette <- c(color_palette, Others = "#B3B3B3")

plot_list <- lapply(unique(combined_df$Group), function(g) {
  ggplot(combined_df %>% filter(Group == g), 
         aes(x = "", y = Total, fill = Species)) +
    geom_col(width = 1, color = "white", linewidth = 0.2) +
    coord_polar(theta = "y") +
    scale_fill_manual(
      values = color_palette, 
      limits = species_levels,
      na.value = "#E0E0E0"
    ) +
    ggtitle(g) +
    theme_void() +
    theme(
      text = element_text(color = "#333333"),
      plot.title = element_text(
        size = 8, 
        face = "bold", 
        hjust = 0.5, 
        margin = margin(t = 2, b = 4)
      ),
      legend.position = "none"
    )
})

legend_plot <- ggplot(combined_df, aes(x = "", y = Total, fill = Species)) +
  geom_col() +
  scale_fill_manual(
    values = color_palette, 
    limits = species_levels, 
    name = "Species"
  ) +
  theme_void() +
  theme(
    text = element_text(color = "#333333"),
    legend.text = element_text(size = 7),
    legend.title = element_text(size = 8, face = "bold"),
    legend.key.size = unit(3, "mm"),
    legend.spacing.y = unit(2, "mm"),
    legend.position = "right",
    legend.direction = "vertical",
    plot.margin = margin(0, 0, 0, 0)
  )

legend_final <- get_legend(legend_plot)

p6 <- plot_grid(
  plot_grid(plotlist = plot_list, ncol = 4, align = "v", axis = "tb"),
  legend_final,
  ncol = 2,
  rel_widths = c(4, 1.2),
  align = "h"
)


final_plot <- plot_grid(
  combined_plot,
  p6,
  nrow = 2,
  align = "v",
  rel_heights = c(2, 1)
) + theme(plot.margin = unit(c(0,0,0,0), "cm"))


width<-20
height<-28
ggsave("./Figure/Figure6.pdf",plot = final_plot,width = width,height = height,units = "cm",dpi = 600,paper = "a4")
ggsave("./Figure/Figure6.png",plot = final_plot,width = width,height = height,units = "cm",dpi = 600)

```