---
title: "script"
author: "jincanzhi"
date: "2025-12-17"
output: html_document
---

```{r setup, include=FALSE}
library(treeio)
library(dplyr)
library(tibble)
library(ggplot2)
library(ggtree)
library(ggtreeExtra)
library(ggnewscale)   
library(rstatix)
library(agricolae)
library(vegan)
library(cowplot)
library(patchwork)
library(ggsignif)
set.seed(113)
knitr::opts_knit$set(root.dir =dirname(rstudioapi::getSourceEditorContext()[["path"]]))
```

##Figure1A
```{r}
tree <- treeio::read.newick("./data/merged.rename.nwk",node.label = "support")
group_file<-read.csv("./data/MAG_info.csv",row.names = 1)
label<-tree@phylo$tip.label
group_file <- group_file[rownames(group_file) %in% label,]
group_file <- group_file %>%
  rownames_to_column("bin") %>%
  add_count(Phylum, name = "freq") %>% 
  mutate(Phylum_new = if_else(
    Phylum %in% head(levels(reorder(Phylum, -freq)), 10), 
    as.character(Phylum), 
    "Others"
  )) %>%
  mutate(Phylum_new = factor(
    Phylum_new,
    levels = c(head(levels(reorder(Phylum, -freq)), 10), "Others")
  )) %>%
  select(-freq) %>%
  column_to_rownames("bin")
groupInfo <- split(row.names(group_file), group_file$Phylum_new)
tree <- groupOTU(tree, groupInfo)
group <- group_file
if (!exists("is.waive")) {
  is.waive <- \(x) inherits(x, "waiver")
}
p1 <- ggtree(tree,layout = "fan",right = TRUE,open.angle = 15)+
  geom_aline(aes(color=group),linetype = "solid",size=0.05,key_glyph = 'rect',show.legend = TRUE)+
  scale_color_manual(values=c("#FBB4AE","#E5D8BD","#B3CDE3","#FDCDAC","#F2F2F2","#E6F5C9","#FDDAEC","#FED9A6","#FFF2AE","#DECBE4","grey80"), breaks = levels(group_file$Phylum_new)) + 
  guides(
    colour = guide_legend(
      title = "Phylum",
      order = 1,
      title.position = "top",
      title.theme = element_text(
        size = 10,
        margin = margin(b = 20),
        family = "sans",
        colour = "black"
      ),
      nrow = 2,  
    )
  )+
  theme(
    legend.position = "bottom",
    legend.title.position = "left",
    legend.key = element_rect(fill = "white",color = NA),
    legend.key.spacing.y = unit(2,"mm"),
    legend.key.size = unit(1,"line")
  )

abun_plot <- group %>% 
  rownames_to_column("ID") %>%
  mutate(
    RP_sum = log10(RP_sum),
    RS_sum = log10(RS_sum)
  )
rp_min <- min(abun_plot$RP_sum, na.rm = TRUE)
rp_max <- max(abun_plot$RP_sum, na.rm = TRUE)
rp_breaks <- pretty(c(rp_min, rp_max), n = 4)

p2 <- rotate_tree(p1, angle = 100) +
  geom_fruit(
    data = abun_plot,
    geom = geom_tile,
    mapping = aes(y = ID, x = "", fill = RP_sum),
    offset = 0.03,
    width = 0.1,
    pwidth = 0.5
  ) + 
  scale_fill_gradient(
    low = "white", 
    high = "#D55E00",
    breaks = rp_breaks,
    limits = c(rp_min, rp_max),
    name = "Rhizoplane",
    guide = FALSE
  )

p3 <- p2+
  new_scale_fill() + 
  geom_fruit(
    data = abun_plot,
    geom = geom_tile,
    mapping = aes(y = ID, x = "", fill = RP_sum),
    offset = 0.03,
    width = 0.1,
    pwidth = 0.5
  ) + 
  scale_fill_gradient(
    low = "white", 
    high = "#0072B2",
    breaks = rp_breaks,
    limits = c(rp_min, rp_max),
    name = "Rhizoplane",
    guide = FALSE
  )

size_plot <- group %>% 
  rownames_to_column("ID") %>%
  select(ID,size)

p4 <- p3 + geom_fruit(
  data = size_plot,
  geom = geom_bar,
  stat = 'identity',
  width = 0.7,
  aes(y = ID, x=size),
  pwidth = 0.25
)

width<-17.5
height<-27.5
ggsave("./Figure/Figure1A.pdf",plot = p4,width = width,height = height,units = "cm",dpi = 600,paper = "a4")
ggsave("./Figure/Figure1A.png",plot = p4,width = width,height = height,units = "cm",dpi = 600)
```

##Figure1C
```{r}
df <- read.csv("./data/MAG_abundance_sum.csv",row.names = 1)
shannon<- diversity(df,index="shannon", MARGIN = 2)
simpson<- diversity(df,index="simpson", MARGIN = 2)
richness<-specnumber(df, MARGIN = 2)
index <- as.data.frame(cbind(shannon, simpson, richness))
write.table(cbind(sample=c(rownames(index)),index),"./data/MAG.diversity.index.txt", row.names = F, sep = '\t', quote = F)


raw_df <- read.table("./data/MAG.diversity.index.txt", header = TRUE, row.names = 1)
metadata <- read.csv("./data/metadata.csv", row.names = 1)
merge_df <- merge(raw_df, metadata, by.x = "row.names", by.y = "row.names")
fin_df <- merge_df[c("region", "shannon")]
names(fin_df)[1] <- "Group"

fin_df$Group <- factor(fin_df$Group, levels = c("RP", "RS"))

wilcox_res <- wilcox_test(shannon ~ Group, data = fin_df, exact = FALSE,paired = TRUE,alternative = "less")
p_value <- wilcox_res$p

if (p_value < 0.001) {
  sig_label <- "***"
} else if (p_value < 0.01) {
  sig_label <- "**"
} else if (p_value < 0.05) {
  sig_label <- "*"
} else {
  sig_label <- "ns"
}

p1 <- ggplot(fin_df, aes(x = Group, y = shannon)) + 
  geom_point(aes(color = Group), position = position_jitter(width = 0.15), 
             alpha = 0.8, size = 4, stroke = 0) +
  geom_boxplot(width = 0.3, alpha = 0.2, na.rm = TRUE) +   
  geom_violin(width = 0.5, alpha = 0.2, na.rm = TRUE) +  
  geom_signif(comparisons = list(c("RP", "RS")),
              annotations = sig_label,
              tip_length = 0.02,
              color = "black") +
  theme_classic(base_size = 10) +
  scale_x_discrete(labels = c("Rhizoplane", "Rhizosphere")) + 
  scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  scale_fill_manual(values = c("#D55E00", "#0072B2")) + 
  theme(
    axis.title = element_text(size = 10, color = "black", face = "bold"),
    axis.text = element_text(size = 10, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.ticks = element_line(linewidth = 0.6, color = "black"),
    axis.line = element_line(linewidth = 0.6, color = "black"),
    panel.border = element_rect(fill = NA, color = "black", linewidth = 0.8),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    legend.position = "none"
  ) + 
  labs(
    x = NULL,
    y = "Shannon"
  )+ 
  coord_cartesian(ylim = c(NA, max(fin_df$shannon, na.rm = TRUE) * 1.02))

fin_df <- merge_df[c("region", "simpson")]
names(fin_df)[1] <- "Group"

fin_df$Group <- factor(fin_df$Group, levels = c("RP", "RS"))

wilcox_res <- wilcox_test(simpson ~ Group, data = fin_df, exact = FALSE,paired = TRUE,alternative = "less")
p_value <- wilcox_res$p

if (p_value < 0.001) {
  sig_label <- "***"
} else if (p_value < 0.01) {
  sig_label <- "**"
} else if (p_value < 0.05) {
  sig_label <- "*"
} else {
  sig_label <- "ns"
}


p2 <- ggplot(fin_df, aes(x = Group, y = simpson)) + 
  geom_point(aes(color = Group), position = position_jitter(width = 0.15), 
             alpha = 0.8, size = 4, stroke = 0) +
  geom_boxplot(width = 0.3, alpha = 0.2, na.rm = TRUE) +   
  geom_violin(width = 0.5, alpha = 0.2, na.rm = TRUE) +  
  geom_signif(comparisons = list(c("RP", "RS")),
              annotations = sig_label,
              tip_length = 0.02,
              color = "black") +
  theme_classic(base_size = 10) +
  scale_x_discrete(labels = c("Rhizoplane", "Rhizosphere")) + 
  scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  scale_fill_manual(values = c("#D55E00", "#0072B2")) + 
  theme(
    axis.title = element_text(size = 10, color = "black", face = "bold"),
    axis.text = element_text(size = 10, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.ticks = element_line(linewidth = 0.6, color = "black"),
    axis.line = element_line(linewidth = 0.6, color = "black"),
    panel.border = element_rect(fill = NA, color = "black", linewidth = 0.8),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    legend.position = "none"
  ) + 
  labs(
    x = NULL,
    y = "Simpson"
  )+ 
  coord_cartesian(ylim = c(NA, max(fin_df$simpson, na.rm = TRUE) * 1.005))


##beta
ko_abundance <- read.csv("./data/MAG_abundance_sum.csv", row.names = 1, stringsAsFactors = FALSE)
metadata <- read.csv("./data/metadata.csv", row.names = 1, stringsAsFactors = FALSE)

ko_t <- t(ko_abundance)
bray_dist <- vegdist(ko_t, method = "bray", na.rm = TRUE)


pcoa_sig <- adonis2(bray_dist ~ region, data = metadata, permutations = 1000)
variance <- pcoa_sig['Model', 'R2']
p.val <- pcoa_sig['Model', 'Pr(>F)']

cmdscale_total <- cmdscale(bray_dist, eig = T)
eig <- cmdscale_total$eig

points <- data.frame(cmdscale_total$points)
data_df <- cbind(points, Group = metadata[rownames(points),])%>%
  mutate(Group.region = case_when(
    Group.region == "RP" ~ "Rhizoplane",
    Group.region == "RS" ~ "Rhizosphere",
    TRUE ~ Group.region
  ))
names(data_df)[names(data_df) == "Group.region"] <- "region"

p_text <- ifelse(p.val < 0.001, "p < 0.001", 
                 ifelse(p.val < 0.01, "p < 0.01", 
                        ifelse(p.val < 0.05, "p < 0.05", paste0("p = ", format(p.val, digits = 2)))))

p3<- ggplot(data_df, aes(x = X1, y = X2, color = region)) + 
    geom_point(size = 4, alpha = 1) + 
    stat_ellipse(level = 0.95, type = "norm", linewidth = 0.8, show.legend = FALSE) +
    labs(x = paste('PCoA 1 (', format(100*eig[1]/sum(eig), digits=4), '%)', sep = ''),
         y = paste('PCoA 2 (', format(100*eig[2]/sum(eig), digits=4), '%)', sep = '')) + 
    ggtitle(paste(format(100*variance, digits = 3), '% of variance; ', p_text, sep = '')) +
    scale_color_manual(values = c("#D55E00", "#0072B2")) + 
    scale_fill_manual(
        values = c("#D55E00", "#0072B2"),
        labels = c("Rhizoplane", "Rhizosphere"),
        name = "Region"
    ) +
    theme_classic(base_size = 10) +
    theme(plot.title = element_text(size = 10, color = 'black', hjust = 0.5), 
          plot.subtitle = element_text(size = 10, color = 'black', hjust = 0.5), 
          axis.title = element_text(size = 10, color = "black", face = "bold"),
          axis.text = element_text(size = 10, color = "black"),
          axis.ticks = element_line(linewidth = 0.6, color = "black"),
          axis.line = element_line(linewidth = 0.6, color = "black"),
          panel.border = element_rect(
            fill = NA, color = "black", linewidth = 0.8
          ),
          panel.grid = element_blank(),
          panel.background = element_blank(),
          legend.key.size = unit(0.5, 'cm'),
          legend.box.spacing = unit(0.5,"cm"),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          legend.position = 'none')

combined_plot <- (p1 + p2 + p3) + 
  plot_layout(
    nrow = 1,
    widths = c(1, 1, 2),
    heights = c(1, 1, 1)
  )

width<-21
height<-10
ggsave("./Figure/Figure1CDE.pdf",plot = combined_plot,width = width,height = height,units = "cm",dpi = 600,paper = "a4")
ggsave("./Figure/Figure1CDE.png",plot = combined_plot,width = width,height = height,units = "cm",dpi = 600)
```
