---
title: "script"
author: "jincanzhi"
date: "2025-11-20"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(ggvenn)
library(rstatix)
library(agricolae)
library(patchwork) 
knitr::opts_knit$set(root.dir =dirname(rstudioapi::getSourceEditorContext()[["path"]]))
```


##Figure2C
```{r}
df_RP <- read.csv("./data/RP_MAG_network_hub_info.csv",row.names = 1)
df_RS <- read.csv("./data/RS_MAG_network_hub_info.csv",row.names = 1)


mag_list <- list(
  RP = rownames(df_RP),
  RS = rownames(df_RS)
)

venn_plot <- ggvenn(
  mag_list,
  fill_color = c("#D55E00", "#0072B2"),
  fill_alpha = 0.7,
  stroke_color = "white",
  stroke_size = 0.8,
  set_name_size = 5,
  text_size = 5,
  show_percentage = TRUE,
  digits = 2
)

ggsave("./Figure/Figure2C.pdf",plot = venn_plot,width = 5,height = 5,dpi = 300)
ggsave("./Figure/Figure2C.png",plot = venn_plot,width = 5,height = 5,dpi = 300)

```

##Figure2D
```{r}
RP_hub <- read.csv("./data/RP_MAG_network_hub_info.csv",row.names = 1)
RS_hub <- read.csv("./data/RS_MAG_network_hub_info.csv",row.names = 1)

rp_part <- data.frame(
  type = "RP",
  degree = RP_hub$igraph.degree
)
rs_part <- data.frame(
  type = "RS",
  degree = RS_hub$igraph.degree
)

fin_df <- rbind(rp_part, rs_part)

names(fin_df)[1] <- 'Group'
max_df <- aggregate(fin_df['degree'], by = list(Group = fin_df$Group), FUN = max)
mean_df <- aggregate(fin_df['degree'], by = list(Group = fin_df$Group), FUN = mean)
dunn_res <- dunn_test(fin_df, degree ~ Group, p.adjust.method = 'fdr')
dunn_res_df <- data.frame(dunn_res[-1])
n <- nrow(mean_df)
pvalue_df <- matrix(1, ncol = n, nrow = n)
k <- 0
for(i in 1:(n - 1)) { 
  for(j in (i + 1):n){ 
    k <- k + 1
    pvalue_df[i,j] <- dunn_res_df$p.adj[k]
    pvalue_df[j,i] <- dunn_res_df$p.adj[k]
  }
}
letter_df <- orderPvalue(mean_df$Group, mean_df$degree, 0.05, pvalue_df, console = TRUE)
letter_vector <- letter_df$groups
max_degree <- max(fin_df$degree)
p <- ggplot(fin_df, aes(x = Group, y = degree, color = Group)) + 
  geom_violin(
    aes(fill = Group), 
    width = 0.6, alpha = 0.2, size = 0.5, 
    show.legend = FALSE
  ) + 
  geom_boxplot(
    width = 0.25, alpha = 0.3, size = 0.6, 
    outlier.shape = NA,
    position = position_dodge(width = 0.6),
    show.legend = FALSE
  ) + 
  geom_point(
    position = position_jitterdodge(
      jitter.width = 0.2,
      dodge.width = 0.6
    ), 
    alpha = 0.7, size = 2, stroke = 0.3,
    show.legend = FALSE
  ) + 
  geom_text(
    data = mean_df, 
    aes(y = max_degree * 1.1, label = letter_vector), 
    position = position_dodge(width = 0.6), 
    size = 3, color = "black"
  ) + 
  theme_classic(base_size = 10) + 
  scale_x_discrete(
    labels = c("Rhizoplane", "Rhizosphere"),
    expand = c(0.1, 0.1)
  ) + 
  scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  scale_fill_manual(values = c("#D55E00", "#0072B2")) + 
  theme(
    axis.title = element_text(size = 11, color = "black", face = "bold"),
    axis.text = element_text(size = 9, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.ticks = element_line(linewidth = 0.6, color = "black"),
    axis.line = element_line(linewidth = 0.6, color = "black"),
    panel.border = element_rect(
      fill = NA, color = "black", linewidth = 0.8
    ),
    panel.grid = element_blank(),
    panel.background = element_blank()
  ) + 
  labs(
    x = NULL,
    y = "Degree"
  )
ggsave("./Figure/Figure2D.pdf",plot = p,width = 2,height = 3.5,dpi = 300)
ggsave("./Figure/Figure2D.png",plot = p,width = 2,height = 3.5,dpi = 300)
```

##Figure2E
```{r}
df_RP <- read.csv("./data/RP_MAG_network_hub_info.csv")
df_RS <- read.csv("./data/RS_MAG_network_hub_info.csv")
MAG_info <- read.csv("./data/MAG_info.csv")

common_mags <- intersect(df_RP$X,df_RS$X)
common_df <- MAG_info[MAG_info$name %in% common_mags,]

phylum_counts <- common_df %>%
  count(Phylum, name = "n") %>% 
  arrange(desc(n))

phylum_counts <- common_df %>%
  count(Phylum, name = "n") %>%
  arrange(desc(n)) %>%
  mutate(Phylum = factor(Phylum, levels = .$Phylum))


phylum_colors_df <- read.csv("./data/phylum_color.csv", stringsAsFactors = FALSE)

phylum_color_vector <- phylum_colors_df$color
names(phylum_color_vector) <- phylum_colors_df$Phylum

bar_plot <- ggplot(phylum_counts, aes(x = Phylum, y = n, fill = Phylum)) +
  geom_col(width = 0.7, color = "black", linewidth = 0.2) +
  geom_text(
    aes(label = n),
    vjust = -0.2,
    size = 3,
    color = "black"
  ) +
  scale_fill_manual(values = phylum_color_vector) +
  labs(
    x = "Phylum",
    y = "Number"
  ) +
  theme_classic(base_size = 10) + 
  theme(
    axis.title.y = element_text(size = 11, color = "black", face = "bold"),
    axis.title.x = element_blank(),
    axis.text = element_text(size = 9, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.ticks = element_line(linewidth = 0.6, color = "black"),
    axis.line = element_line(linewidth = 0.6, color = "black"),
    #panel.border = element_rect(fill = NA, color = "black", linewidth = 0.8),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    legend.position = "none"
  )
  
ggsave("./Figure/Figure2E.pdf",plot = bar_plot,width = 7,height = 3.2,dpi = 300)
ggsave("./Figure/Figure2E.png",plot = bar_plot,width = 7,height = 3.2,dpi = 300)
```


##Figure2D-three
```{r}
RP_hub <- read.csv("./data/RP_MAG_network_hub_info.csv",row.names = 1)
RS_hub <- read.csv("./data/RS_MAG_network_hub_info.csv",row.names = 1)

metrics <- c("igraph.degree", "igraph.betweenness", "igraph.closeness")
y_labels <- c("Degree", "Betweenness", "Closeness")


plot_list <- list()
for (i in seq_along(metrics)) {
  curr_metric <- metrics[i]
  curr_ylabel <- y_labels[i]

  rp_part <- data.frame(Group = "RP", Value = RP_hub[[curr_metric]])
  rs_part <- data.frame(Group = "RS", Value = RS_hub[[curr_metric]])
  fin_df <- rbind(rp_part, rs_part)
  
  max_df <- aggregate(Value ~ Group, fin_df, FUN = max)
  mean_df <- aggregate(Value ~ Group, fin_df, FUN = mean)
  
  dunn_res <- dunn_test(fin_df, Value ~ Group, p.adjust.method = "fdr")
  dunn_res_df <- data.frame(dunn_res[-1])
  
  n_group <- nrow(mean_df)
  pvalue_df <- matrix(1, nrow = n_group, ncol = n_group)
  k <- 0
  for (j in 1:(n_group-1)) {
    for (l in (j+1):n_group) {
      k <- k + 1
      pvalue_df[j, l] <- dunn_res_df$p.adj[k]
      pvalue_df[l, j] <- dunn_res_df$p.adj[k]
    }
  }
  
  letter_df <- orderPvalue(mean_df$Group, mean_df$Value, 0.05, pvalue_df, console = TRUE)
  letter_vector <- letter_df$groups
  
  global_max <- max(fin_df$Value)

  p <- ggplot(fin_df, aes(x = Group, y = Value, color = Group)) +
    geom_violin(aes(fill = Group), width = 0.6, alpha = 0.2, size = 0.5, show.legend = FALSE) +
    geom_boxplot(width = 0.25, alpha = 0.3, size = 0.6, outlier.shape = NA, 
                 position = position_dodge(0.6), show.legend = FALSE) +
    geom_point(position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.6), 
               alpha = 0.7, size = 2, stroke = 0.3, show.legend = FALSE) +
    geom_text(data = mean_df, aes(y = global_max * 1.1, label = letter_vector), 
              position = position_dodge(0.6), size = 3, family = "Arial", color = "black") +
    theme_classic(base_size = 10, base_family = "Arial") +
    scale_x_discrete(labels = c("Rhizoplane", "Rhizosphere"), expand = c(0.1, 0.1)) +
    scale_color_manual(values = c("#D55E00", "#0072B2")) +
    scale_fill_manual(values = c("#D55E00", "#0072B2")) +
    theme(
      axis.title = element_text(size = 11, color = "black", face = "bold"),
      axis.text = element_text(size = 9, color = "black"),
      axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
      axis.ticks = element_line(linewidth = 0.6, color = "black"),
      axis.line = element_line(linewidth = 0.6, color = "black"),
      panel.border = element_rect(fill = NA, color = "black", linewidth = 0.8),
      panel.grid = element_blank(),
      panel.background = element_blank()
    ) +
    labs(x = NULL, y = curr_ylabel)
  plot_list[[i]] <- p
}

combined_plot <- wrap_plots(plot_list, nrow = 1) + 
  plot_annotation(tag_levels = "a", tag_suffix = ".") &
  theme(plot.tag = element_text(size = 12, face = "bold"))
```