---
title: "script"
author: "jincanzhi"
date: "2025-12-24"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tibble)
library(vegan)
library(rstatix)
library(agricolae)
library(patchwork)
library(tidyr) 
library(ggsignif)
library(cowplot)
library(ReporterScore)
set.seed(113)
knitr::opts_knit$set(root.dir =dirname(rstudioapi::getSourceEditorContext()[["path"]]))
```

```{r}
##alpha
raw_df <- read.table("./data/KO.diversity.index.txt",header=T,row.names = 1)
metadata <- read.csv("./data/metadata.csv",row.names = 1)
merge_df <- merge(raw_df, metadata, by.x = 'row.names', by.y = 'row.names')
fin_df <- merge_df[c("region", "shannon")]
names(fin_df)[1] <- "Group"

fin_df$Group <- factor(fin_df$Group, levels = c("RP", "RS"))

wilcox_res <- wilcox_test(shannon ~ Group, data = fin_df, exact = FALSE,paired = TRUE,alternative = "greater")
p_value <- wilcox_res$p

if (p_value < 0.001) {
  sig_label <- "***"
} else if (p_value < 0.01) {
  sig_label <- "**"
} else if (p_value < 0.05) {
  sig_label <- "*"
} else {
  sig_label <- "ns"
}

p1 <- ggplot(fin_df, aes(x = Group, y = shannon)) + 
  geom_point(aes(color = Group), position = position_jitter(width = 0.15), 
             alpha = 0.8, size = 4, stroke = 0) +
  geom_boxplot(width = 0.3, alpha = 0.2, na.rm = TRUE) +   
  geom_violin(width = 0.5, alpha = 0.2, na.rm = TRUE) +  
  geom_signif(comparisons = list(c("RP", "RS")),
              annotations = sig_label,
              tip_length = 0.02,
              color = "black") +
  theme_classic(base_size = 10) +
  scale_x_discrete(labels = c("Rhizoplane", "Rhizosphere")) + 
  scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  scale_fill_manual(values = c("#D55E00", "#0072B2")) + 
  theme(
    axis.title = element_text(size = 10, color = "black", face = "bold"),
    axis.text = element_text(size = 10, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.ticks = element_line(linewidth = 0.6, color = "black"),
    axis.line = element_line(linewidth = 0.6, color = "black"),
    panel.border = element_rect(fill = NA, color = "black", linewidth = 0.8),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    legend.position = "none"
  ) + 
  labs(
    x = NULL,
    y = "Shannon"
  )+ 
  coord_cartesian(ylim = c(NA, max(fin_df$shannon, na.rm = TRUE) * 1.01))

fin_df <- merge_df[c("region", "simpson")]
names(fin_df)[1] <- "Group"

fin_df$Group <- factor(fin_df$Group, levels = c("RP", "RS"))

wilcox_res <- wilcox_test(simpson ~ Group, data = fin_df, exact = FALSE,paired = TRUE,alternative = "greater")
p_value <- wilcox_res$p

if (p_value < 0.001) {
  sig_label <- "***"
} else if (p_value < 0.01) {
  sig_label <- "**"
} else if (p_value < 0.05) {
  sig_label <- "*"
} else {
  sig_label <- "ns"
}


p2 <- ggplot(fin_df, aes(x = Group, y = simpson)) + 
  geom_point(aes(color = Group), position = position_jitter(width = 0.15), 
             alpha = 0.8, size = 4, stroke = 0) +
  geom_boxplot(width = 0.3, alpha = 0.2, na.rm = TRUE) +   
  geom_violin(width = 0.5, alpha = 0.2, na.rm = TRUE) +  
  geom_signif(comparisons = list(c("RP", "RS")),
              annotations = sig_label,
              tip_length = 0.02,
              color = "black") +
  theme_classic(base_size = 10) +
  scale_x_discrete(labels = c("Rhizoplane", "Rhizosphere")) + 
  scale_color_manual(values = c("#D55E00", "#0072B2")) + 
  scale_fill_manual(values = c("#D55E00", "#0072B2")) + 
  theme(
    axis.title = element_text(size = 10, color = "black", face = "bold"),
    axis.text = element_text(size = 10, color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    axis.ticks = element_line(linewidth = 0.6, color = "black"),
    axis.line = element_line(linewidth = 0.6, color = "black"),
    panel.border = element_rect(fill = NA, color = "black", linewidth = 0.8),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    legend.position = "none"
  ) + 
  labs(
    x = NULL,
    y = "Simpson"
  )+ 
  coord_cartesian(ylim = c(NA, max(fin_df$simpson, na.rm = TRUE) * 1.0001))

##beta
ko_abundance <- read.delim("./data/Bacteria.kegg.anno.profile", row.names = 1, stringsAsFactors = FALSE)
metadata <- read.csv("./data/metadata.csv", row.names = 1, stringsAsFactors = FALSE)
ko_t <- t(ko_abundance)
bray_dist <- vegdist(ko_t, method = "bray", na.rm = TRUE)


pcoa_sig <- adonis2(bray_dist ~ region, data = metadata, permutations = 1000)
variance <- pcoa_sig['Model', 'R2']
p.val <- pcoa_sig['Model', 'Pr(>F)']

cmdscale_total <- cmdscale(bray_dist, eig = T)
eig <- cmdscale_total$eig

points <- data.frame(cmdscale_total$points)
data_df <- cbind(points, Group = metadata[rownames(points),])%>%
  mutate(Group.region = case_when(
    Group.region == "RP" ~ "Rhizoplane",
    Group.region == "RS" ~ "Rhizosphere",
    TRUE ~ Group.region
  ))
names(data_df)[names(data_df) == "Group.region"] <- "region"

p_text <- ifelse(p.val < 0.001, "p < 0.001", 
                 ifelse(p.val < 0.01, "p < 0.01", 
                        ifelse(p.val < 0.05, "p < 0.05", paste0("p = ", format(p.val, digits = 2)))))

p3<- ggplot(data_df, aes(x = X1, y = X2, color = region)) + 
    geom_point(size = 4, alpha = 1) + 
    stat_ellipse(level = 0.95, type = "norm", linewidth = 0.8, show.legend = FALSE) +
    labs(x = paste('PCoA 1 (', format(100*eig[1]/sum(eig), digits=4), '%)', sep = ''),
         y = paste('PCoA 2 (', format(100*eig[2]/sum(eig), digits=4), '%)', sep = '')) + 
    ggtitle(paste(format(100*variance, digits = 3), '% of variance; ', p_text, sep = '')) +
    scale_color_manual(values = c("#D55E00", "#0072B2")) + 
    scale_fill_manual(
        values = c("#D55E00", "#0072B2"),
        labels = c("Rhizoplane", "Rhizosphere"),
        name = "Region"
    ) +
    theme_classic(base_size = 10) +
    theme(plot.title = element_text(size = 10, color = 'black', hjust = 0.5), 
          plot.subtitle = element_text(size = 10, color = 'black', hjust = 0.5), 
          axis.title = element_text(size = 10, color = "black", face = "bold"),
          axis.text = element_text(size = 10, color = "black"),
          axis.ticks = element_line(linewidth = 0.6, color = "black"),
          axis.line = element_line(linewidth = 0.6, color = "black"),
          panel.border = element_rect(
            fill = NA, color = "black", linewidth = 0.8
          ),
          panel.grid = element_blank(),
          panel.background = element_blank(),
          legend.key.size = unit(0.5, 'cm'),
          legend.box.spacing = unit(0.5,"cm"),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          legend.position = 'none')

combined_plot <- (p1 + p2 + plot_spacer()+p3) + 
  plot_layout(
    nrow = 1,
    widths = c(2, 2, 1, 4),
    heights = c(1, 1, 1, 1)
  )



###GSRE
set.seed(113)
KO_abun <- read.delim("./data/Bacteria.kegg.anno.profile",row.names = 1)
KO_name <- read.csv("C:/Users/jincanzhi/Desktop/kegg/K_gene_name.csv",header =  T)
metadata<-read.csv(file="./data/metadata.csv",header=T,row.names = 1)
reporter_res=reporter_score(KO_abun,"region",metadata,mode="directed",method = "wilcox.test", perm = 999,p.adjust.method1 = "fdr",p.adjust.method2 = "fdr")
pathway_enrich <- reporter_res$reporter_s
pathway_name <- read.csv("C:/Users/jincanzhi/Desktop/kegg/pathway_Bacteria.csv",header =  F)
pathway_info <- read.csv("C:/Users/jincanzhi/Desktop/kegg/kegg_info_0508filter.csv")
pathway_name$V1 <- gsub("ko", "map", pathway_name$V1)
pathway_enrich <- pathway_enrich[pathway_enrich$ID %in% pathway_name$V1,]
pathway_enrich <- pathway_enrich[pathway_enrich$ID %in% pathway_info$L3,]
write.csv(pathway_enrich,file=paste0("./data/enrich_pathway_list.csv"))
enrich_KO<-reporter_res$ko_stat
enrich_KO <- merge(enrich_KO,KO_name,by.x = "KO_id",by.y = "KO",all.x = T)
write.csv(enrich_KO,file=paste0("./data/enrich_KO_stat.csv"))

filtered_data <- na.omit(pathway_enrich[pathway_enrich$p.adjust <0.05,])
sorted_data <- filtered_data[order(filtered_data$ReporterScore), ]
sorted_data$Description <- factor(sorted_data$Description, levels = unique(sorted_data$Description))
#write.csv(sorted_data,"./data/Reportercsore.csv")


data <- read.csv("./data/Reportercsore.csv")
data$Enrich <- ifelse(data$ReporterScore > 0,"RS","RP")
p4 <- ggplot(data, 
           aes(x = reorder(Description, ReporterScore), 
               y = ReporterScore,
               fill = Enrich)) +
  geom_bar(stat = "identity", 
           color = "black",
           linewidth = 0.3,
           width = 0.8) +
  scale_fill_manual(
    values = c("#D55E00", "#0072B2"),
    labels = c("Rhizoplane", "Rhizosphere"),
    name = ""
  ) +
  theme_bw(base_size = 10) +
  theme(
    axis.title = element_text(face = "bold", size = 10),
    axis.text.x = element_text(angle = 90,hjust = 1,vjust = 0.5,size = 10,color = 'black'),
    axis.text.y = element_text(size = 10,margin = margin(r = 5)),
    panel.grid = element_blank(),
    panel.border = element_rect(linewidth = 0.5),
    plot.margin = unit(c(0,0,0,0), "cm"),
    legend.position = "top",
    legend.title = element_text(face = "bold"),
    legend.key.size = unit(0.5, "cm")
  ) +
  labs(
    y = "Reporter Score", 
    x = "")   


final_plot <- plot_grid(
  combined_plot,
  p4,
  nrow = 2,
  align = "v",
  rel_heights = c(1, 2)
)

  
height <-28
width <- 20
ggsave("./Figure/Figure4.pdf",plot = final_plot,width = width,height = height,units = "cm",dpi = 600,paper="a4")
ggsave("./Figure/Figure4.png",plot = final_plot,width = width,height = height,units = "cm",dpi = 600)

```